spring:
  profiles.active: dev
  jpa:
    open-in-view: true

server:
  port: 8080
#  servlet:
#    context-path: /plantones_resource_srvr

  # *******Logging*******
logging:
  level:
    root: INFO
    org.springframework: INFO
    springframework:
      security: DEBUG

  # *******OAuth Config*******
  #security.oauth2.resource.user-info-uri=http://localhost:8282/plantones_auth_srvr/user

  #spring.main.allow-bean-definition-overriding=true
management:
  endpoints:
    web:
      exposure:
        include: "*"
---
spring:
  config:
    activate:
      on-profile: dev
#  datasource:
#    url: jdbc:mysql://localhost/curso-spring-db
#    username: leopinheiro
#    password: T72Fyub&r4jilKEW
  devtools:
    add-properties: true
#  jpa:
#    hibernate:
#      ddl-auto: update
#    show-sql: true
#    properties:
#      hibernate:
#        jdbc:
#          lob:
#            non_contextual_creation: true
#        format_sql: true

#  jwt.secret: MYJWTSECRET
#  jwt.expiration: 3600000
flyway:
  validate-on-migrate: true
  url: ${spring.datasource.url}
  user: ${spring.datasource.username}
  password: ${spring.datasource.password}
#  schemas:


---
spring:
  config:
    activate:
      on-profile: test
  datasource:
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1
    username: sa
    password:
  flyway:
    enabled: false
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: update
logging:
  level:
    root: WARN
#    org.springframework: WARN
#    springframework:
#      security: INFO


